### ISSUE TITLE
Kind List resources cannot be reconciled

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/reconciler#1027]
**Description**

The monitoring component has a specific override 'additionalPrometheusRules' which will render additional rules using a resource of kind List. That resource kind let the reconcilation fail.

To reproduce the problem call the CLI with:
```
kyma deploy --verbose -f values.yaml
```
where values.yaml contains:
```
monitoring:
  additionalPrometheusRules: |-
   my-rules:
     groups:
       - name: my-group
         rules:
          - alert: ScrapeLimitForTargetExceeded
            annotations:
              description: One or more targets in the job monitoring-prometheus-istio-server have scrape limit exceeded
              summary: Scrape limit for one or more targets is exceeded.
            expr: increase(prometheus_target_scrapes_exceeded_sample_limit_total{job="monitoring-prometheus-istio-server"}[1m]) > 0
            for: 10m
```

The command will fail with the message
```
kubeClient failed to update List 'monitoring-additional-prometheus-rules' (namespace: kyma-system)  with strategy 'PATCH': failed to create resource: the server could not find the requested resource'
```

where the resource with name `monitoring-additional-prometheus-rules` gets rendered only having that specific override active.

Using the dry-run feature `kyma deploy --dry-run -f values.yaml > out.yaml` you can see that the resource gets rendered proper:
```
apiVersion: v1
kind: List
metadata:
  name: monitoring-additional-prometheus-rules
  namespace: kyma-system
items:
  - apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: monitoring-my-group
      namespace: kyma-system
   ...
```

**Expected result**
Reconciler should be able to apply the properly rendered resource

**Actual result**
It fails

**Steps to reproduce**
See description

**Troubleshooting**
There is no simple workaround by using overrides.
Use the dry-run feature to get the rendered resource definitions, deploy kyma without the override, apply the rendered resource manually after the installation
