### ISSUE TITLE
Reconciler can't handle boolean values properly

### ISSUE THREAD

**Issue by pbochynski** [kyma-incubator/reconciler#138]
**Description**

Boolean flags in charts are not properly handled. Example from tracing chart:
```
{{- if .Values.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "jaeger-operator.fullname" . }}
  labels:
{{ include "jaeger-operator.labels" . | indent 4 }}
spec:
  hosts:
  - jaeger.{{ .Values.global.ingress.domainName }}
...
```
Such resource should not be rendered if you set virtualservice.enabled to false.

**Expected result**

Virtual service is not rendered.

**Actual result**

Error:
```
Default-reconciliation of 'tracing' with version 'main' failed: Failed to get manifest for component 'tracing' in Kyma version 'main': Failed to render HELM template for component 'tracing': template: tracing/templates/kyma-additions/virtualservice.yaml:10:21: executing "tracing/templates/kyma-additions/virtualservice.yaml" at <.Values.global.ingress.domainName>: nil pointer evaluating interface {}.domainName
```

**Steps to reproduce**

Run reconciler with such command:
```
./bin/reconciler-darwin local  --components tracing --value tracing.virtualservice.enabled=false 
```

**Links**
This PR demonstrates the issue: https://github.com/kyma-incubator/reconciler/pull/139
