### ISSUE TITLE
Pipeline `kyma-prow-logs/logs/nightly-main-reconciler-e2e` failing: `RECONCILE_STATUS_URL is invalid`

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-incubator/reconciler#1422]
**Description**

- Pipeline `kyma-prow-logs/logs/nightly-main-reconciler-e2e` is failing
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e

```yaml
Request body:
{
  "runtimeID": "6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5",
  "runtimeInput": {
    "name": "demo",
    "description": "",
    "labels": {
      "scenarios": [
        "DEFAULT"
      ]
    }
  },
  "kymaConfig": {
    "version": "main",
    "profile": "Evaluation",
    "components": [],
    "administrators": [
      "test2@test.pl"
    ]
  },
  "metadata": "",
  "kubeconfig": ""
}
sending reconciliation request to mothership-reconciler at: http://reconciler-mothership-reconciler.reconciler/v1/clusters
RECONCILE_STATUS_URL: null
reconciliation request failed: RECONCILE_STATUS_URL is invalid
command terminated with exit code 1
```
