### ISSUE TITLE
Reconciler overwrites namespace even if it is set

### ISSUE THREAD

**Issue by pbochynski** [kyma-incubator/reconciler#158]
**Description**

Helm overwrites namespace for the resource only if it is not set explicitly. Reconciler does it always. 
For example certificates chart should be rendered this way:
```
helm template certificates certificates -n kyma-system --set global.domainName=test.example.com
```
The output is:
```
---
# Source: certificates/templates/certificate.yaml
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: kyma-tls-cert
  namespace: istio-system
spec:
  commonName: "*.test.example.com"
  secretName: kyma-gateway-certs
---
# Source: certificates/templates/gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kyma-gateway
  namespace: kyma-system
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: kyma-gateway-certs
      minProtocolVersion: TLSV1_2
      cipherSuites:
      - ECDHE-RSA-CHACHA20-POLY1305
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-SHA
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-SHA
    hosts:
      - "*.test.example.com"
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true # automatic 301 redirect from http to https
    hosts:
      - "*.test.example.com"
```

**Expected result**

If the namespace is explicitly set it is preserved (Gateway is installed in kyma-system, Certificate is installed in istio-system)

**Actual result**

All resources are installed in the component namespace (whatever namespace is used for the component)

**Steps to reproduce**

./bin/reconciler-darwin local --components certificates --value global.domainName=test.example.com
