### ISSUE TITLE
Controllers do not recover after token deletion

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/reconciler#358]
**Description**
When deleting a serviceaccount token for a controller, the connectivity to the APIServer will be lost by getting "Unauthorized" responses. The controller do not recover and require a restart.

As an example take the service-catalog-controller-manager. It has a serviceaccount referenced in the deployment definition and with that a volume mount of the related secret gets generated in the pod spec like:

```
  - name: service-catalog-controller-manager-token-4949r
    secret:
      defaultMode: 420
      secretName: service-catalog-controller-manager-token-4949r
```

Deleting that concrete secret will result into a non-working controller indicated by logs like "1 controller.go:368] error getting the cluster info configmap: "Unauthorized"". A new secret with a new ID gets immediately generated but the pod stays unhealthy. Only a manual restart of the pod recovers the situation.

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**
