### ISSUE TITLE
User-defined overrides are of lower priority than values from profiles

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-incubator/reconciler#400]
**Description**
I am using kyma-cli, build from commit: `e5ade15d06a57caddc0463237c31ffbdaed5ea30`
I install Kyma from main branch, commit: `3aa24a88caa2a200197896f8230e79d0a9e0e38e`

I installed Kyma on a Gardener cluster with production profile:
`kyma deploy --profile production -v --source local`

It looks like user-defined overrides can't override values from production profile (probably also evaluation). I can only override (or extend) the configuration defined in `values.yaml`. Profile-defined values are not changing.

**Expected result**
User-defined overrides allow to re-define values from profile

**Actual result**
User-defined overrides can't re-define values from profile

**Steps to reproduce**

1) After installation the `istiod` deployment has HPA configured to 80%, MINPODS=2, MAXPODS=5

```
% kubectl -n istio-system get hpa
NAME                   REFERENCE                         TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
istio-ingressgateway   Deployment/istio-ingressgateway   43%/80%, 5%/80%   3         10        3          14m
istiod                 Deployment/istiod                 1%/80%            2         5         2          14m
```

2) Try to override HPA settings for `istiod`

With the command: `kyma deploy -v -p production --component istio-configuration@istio-system --source local --values-file ./values.yaml`

Using the `values.yaml` file:
```
istio-configuration:
  components:
    pilot:
      config:
        hpaSpec:
          maxReplicas: 4
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 33
            type: Resource
```

The result is that `targetAverageUtilization` is changed, but `maxReplicas` is NOT. The `maxReplicas` (MAXPODS) value of `5` comes from production profile:
```
% kubectl -n istio-system get hpa
NAME                   REFERENCE                         TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
istio-ingressgateway   Deployment/istio-ingressgateway   43%/80%, 4%/80%   3         10        3          17m
istiod                 Deployment/istiod                 1%/33%            2         5         2          17m
```

3) When skipping the `-p` flag, I can override both `targetAverageUtilization` and`maxReplicas`

With the command: `kyma deploy -v --component istio-configuration@istio-system --source local --values-file ./values.yaml`
Using the `values.yaml`:
```
istio-configuration:
  components:
    pilot:
      config:
        hpaSpec:
          maxReplicas: 4
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 44
            type: Resource
```
The result is both `targetAverageUtilization` and`maxReplicas` (MAXPODS) are overridden:
```
i303773@C02FC4VPMD6T kcp % kubectl -n istio-system get hpa
NAME                   REFERENCE                         TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
istio-ingressgateway   Deployment/istio-ingressgateway   42%/80%, 5%/80%   1         5         3          28m
istiod                 Deployment/istiod                 4%/44%            1         4         1          28m
```

**Troubleshooting**
n/a
