### ISSUE TITLE
Istio reconciler support istio 1.13.x

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/reconciler#935]
**Description**

Implement necessary changes to install / upgrade istio in 1.13 version. For this story we do not need multiple version support. 

- [x] istioctl 1.13.x is used for installation / upgrade
- [x] istio webhook patching updated if needed
- [x] gardener cluster can be hibernated
- [x] istio running in 1.13.x version
- [x] sidecars running in 1.13.x version
- [x] reconciler bumped in kyma cli

**Reasons**

Keeping Istio up to date

**Attachments**
https://github.com/kyma-project/test-infra/issues/5109

**Comment by mjakobczyk** [comment]
Tested installation with images available after bump from here:
- https://github.com/kyma-project/test-infra/pull/5202

Local Istio chart config that got adjusted for testing purposes looked this way:
```yaml
# the rest of the config
# ...

global:
  containerRegistry:
    path: eu.gcr.io/kyma-project
  images:
    # these definitions aren't used by the chart, but they are required by external tool for list generation
    istio_proxyv2:
      name: "proxyv2"
      version: "1.13.2-distroless"
      directory: "external/istio"
      containerRegistryPath: "eu.gcr.io/kyma-project"
    istio_pilot:
      name: "pilot"
      version: "1.13.2-distroless"
      directory: "external/istio"
      containerRegistryPath: "eu.gcr.io/kyma-project"
  tracing:
    enabled: true
```

So far so good. I did not encounter any problems with installation or upgrade:

```bash
{"level":"INFO","time":"2022-04-07T13:16:10.853+0200","message":"Istio in version 1.13.2-distroless successfully installed"}
{"level":"INFO","time":"2022-04-07T13:16:16.275+0200","message":"Component 'istio' has status 'running'"}
{"level":"INFO","time":"2022-04-07T13:16:27.154+0200","message":"Found 1 pods with different istio proxy image ({istio/proxyv2 1.13.2-distroless-distroless})"}
{"level":"INFO","time":"2022-04-07T13:16:41.972+0200","message":"Proxy reset for 1 pods successfully done"}
{"level":"INFO","time":"2022-04-07T13:16:41.972+0200","message":"Component 'istio' has status 'success'"}
```
